version: '3.8'
services:
  app:
    build:
      context: ../../1_src
      target: local-stage
    image: ci2-cris:local
    container_name: ci2-cris
    stdin_open: true
    tty: true
    restart: unless-stopped
    working_dir: /app
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: ci2_cris
      DB_USER: root 
      DB_PASSWORD: password
    volumes:
      - ../../1_src:/app
    ports:
      - 3000:3000
    depends_on:
      - mariadb
    command: sh -c "rm -f tmp/pids/server.pid && bin/dev"

  mariadb:
    image: mariadb:focal
    container_name: mariadb-ci2-cris
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../../1_src/db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - '3306'
